### ISSUE TITLE
'memory not mapped' error for ComputeMotifScore()

### ISSUE THREAD

**Issue by danliangunc** [sunyoungshin/atSNP#45]
Hi,

When I was using this function ComputeMotifScore() from atSNP, I got the following error for specific SNPs.

>  *** caught segfault ***
> address 0x281b96a7b8, cause 'memory not mapped'
> 
> Traceback:
>  1: motif_score_par(i = 1, par.k = k, par.ncores = ncores, par.motifs = motifs,     par.nmotifs = nmotifs, par.snpids = snpids, par.snpbases = snpbases,     par.len_seq = len_seq, par.motif.lib = motif.lib, par.snp.info = snp.info)
>  2: ComputeMotifScore(total_motif, snp_info, ncores = 1)

Here is my code
```
library(BSgenome.Hsapiens.UCSC.hg38);
library(atSNP);
options(stringsAsFactors=FALSE);
##load ENCODE motifs (encode_motif)
data(encode_library);
## load JASPAR PWMs (jaspar_motif)
data(jaspar_library);
##merge two datasets
total_motif=c(encode_motif, jaspar_motif);
snp_info <- LoadSNPData("thissnplist.txt", genome.lib = "BSgenome.Hsapiens.UCSC.hg38",half.window.size= 30, default.par = TRUE, mutation = TRUE);
## Compute affinity scores
atsnp.scores <- ComputeMotifScore(total_motif, snp_info, ncores = 1);

```

My SNP list only contains one SNP, the txt file is like this

> snpid a1 a2 chr snp
> rs148595936 C T chr1 101089752

Not sure what is the problem, any suggestion?
Thanks!

Dan

**Comment by danliangunc** [comment]
I think it may be a bug, because I found the reason is when the allele is T, the will be 'TRUE' in the function, so the representing number for the allele will be 'NA'. I  fix it by inputting the representing number by myself.

**Comment by sunyoungshin** [comment]
@danliangunc Thank you for the report. I just fixed the issue, so that 'T' is not recognized as 'TRUE'.

**Comment by drneavin** [comment]
Hello,

I am having this same issue. Here is the error that I receive:
```*** caught segfault ***
address 0x56100e46fdc8, cause 'memory not mapped'

Traceback:
 1: motif_score_par(i = 1, par.k = k, par.ncores = ncores, par.motifs = motifs,     par.nmotifs = nmotifs, par.snpids = snpids, par.snpbases = snpbases,     par.len_seq = len_seq, par.motif.lib = motif.lib, par.snp.info = snp.info)
 2: ComputeMotifScore(motif_library, snp_files[["iPSC_GAPDHlo_SNHG8hi"]],     ncores = 1)
```

I tried installing from both bioconductor and github but have the same issue regardless. I think this is the same problem not only because I get the same error message but also because it works when I run without SNPs that have a T as one allele. Please let me know if this is the same problem and if you have any suggestions for me to fix this.

Thanks,
Drew
