### ISSUE TITLE
'memory not mapped' error

### ISSUE THREAD

**Issue by drneavin** [sunyoungshin/atSNP#50]
Hello,

I am having this same issue as issue #45 . Here is the error that I receive:
```
address 0x56100e46fdc8, cause 'memory not mapped'

Traceback:
 1: motif_score_par(i = 1, par.k = k, par.ncores = ncores, par.motifs = motifs,     par.nmotifs = nmotifs, par.snpids = snpids, par.snpbases = snpbases,     par.len_seq = len_seq, par.motif.lib = motif.lib, par.snp.info = snp.info)
 2: ComputeMotifScore(motif_library, snp_files[["iPSC_GAPDHlo_SNHG8hi"]],     ncores = 1)
```
I tried installing from both bioconductor and github but have the same issue regardless. I think this is the same problem not only because I get the same error message but also because it works when I run without SNPs that have a T as one allele. Please let me know if this is the same problem and if you have any suggestions for me to fix this.

Thanks,
Drew

**Comment by sunyoungshin** [comment]
Hello @drneavin 

Thank you for using atSNP. Can you share your code and data which encountered the error, so I can fix the issue? Thanks.

Sunyoung

**Comment by drneavin** [comment]
Hello Sunyoung,

I realised that my issue is different to the one I referenced before. It is instead because I had some insertions and deletions in my SNP list. It is still running the function but it looks like the error no longer occurs.

Thanks,
Drew
